version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      - QDRANT_HOST=qdrant
      - OLLAMA_HOST=host.docker.internal  # Ollama روی هاست اجرا میشه
    depends_on:
      - qdrant
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage