services:
  embedder:
    build: ./embedder
    ports:
      - "8001:8001"
    # networks:
    #     - sail

  api:
    image: alighasempoor/api:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/app/uploads
      - ./api/app:/app/app
    environment:
      - QDRANT_HOST=qdrant
      - EMBEDDER_HOST=embedder
      - OLLAMA_HOST=172.19.0.1
    depends_on:
      - qdrant
      - embedder
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #     - sail      


  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage  
    # networks:
    #     - sail

# networks:
#     sail:
#         driver: bridge